version: '3'

vars:
  BINARY_PATH: bin/koreyik
  ENTRY_POINT_PATH: cmd/koreyik/main.go

tasks:
  build:
    aliases:
      - b

    cmds:
      - go build -o {{.BINARY_PATH}} {{.ENTRY_POINT_PATH}}
  
  default:
    aliases:
      - run
      - r
    
    cmds:
      - go run {{.ENTRY_POINT_PATH}}
